/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.support.stafforderstuff.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Food service. Represents a row in the &quot;StaffOrderStuff_Food&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.support.stafforderstuff.model.impl.FoodModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.support.stafforderstuff.model.impl.FoodImpl}.
 * </p>
 *
 * @author Anna & Ádám
 * @see Food
 * @see com.liferay.support.stafforderstuff.model.impl.FoodImpl
 * @see com.liferay.support.stafforderstuff.model.impl.FoodModelImpl
 * @generated
 */
public interface FoodModel extends BaseModel<Food> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a food model instance should use the {@link Food} interface instead.
	 */

	/**
	 * Returns the primary key of this food.
	 *
	 * @return the primary key of this food
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this food.
	 *
	 * @param primaryKey the primary key of this food
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the food ID of this food.
	 *
	 * @return the food ID of this food
	 */
	public long getFoodId();

	/**
	 * Sets the food ID of this food.
	 *
	 * @param FoodId the food ID of this food
	 */
	public void setFoodId(long FoodId);

	/**
	 * Returns the company ID of this food.
	 *
	 * @return the company ID of this food
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this food.
	 *
	 * @param CompanyId the company ID of this food
	 */
	public void setCompanyId(long CompanyId);

	/**
	 * Returns the group ID of this food.
	 *
	 * @return the group ID of this food
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this food.
	 *
	 * @param GroupId the group ID of this food
	 */
	public void setGroupId(long GroupId);

	/**
	 * Returns the name of this food.
	 *
	 * @return the name of this food
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this food.
	 *
	 * @param Name the name of this food
	 */
	public void setName(String Name);

	/**
	 * Returns the price of this food.
	 *
	 * @return the price of this food
	 */
	public double getPrice();

	/**
	 * Sets the price of this food.
	 *
	 * @param Price the price of this food
	 */
	public void setPrice(double Price);

	/**
	 * Returns the quantity of this food.
	 *
	 * @return the quantity of this food
	 */
	public double getQuantity();

	/**
	 * Sets the quantity of this food.
	 *
	 * @param Quantity the quantity of this food
	 */
	public void setQuantity(double Quantity);

	/**
	 * Returns the unit of this food.
	 *
	 * @return the unit of this food
	 */
	@AutoEscape
	public String getUnit();

	/**
	 * Sets the unit of this food.
	 *
	 * @param Unit the unit of this food
	 */
	public void setUnit(String Unit);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Food food);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Food> toCacheModel();

	@Override
	public Food toEscapedModel();

	@Override
	public Food toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}